@startuml Class_CU15
!theme plain
allowmixing
left to right direction
skinparam classAttributeIconSize 0

actor "Sistema" as Actor

class "ListenerEventos" as UI <<boundary>> {
  + capturarEvento()
}

class "TrazabilidadController" as Ctrl <<control>> {
  + registrarEvento(datos)
}

class "EventLog" as Ent <<entity>> {
  + id: number
  + actionType: string
  + actorId: number
  + timestamp: datetime
}

Actor -right-> UI
UI -right-> Ctrl
Ctrl -right-> Ent
@enduml
